# Generated by Django 3.1.5 on 2021-01-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catalogmoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('integration', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('plan', models.CharField(max_length=255)),
            ],
        ),
    ]
