# Generated by Django 3.1.5 on 2021-01-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_mooc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogmoc',
            name='discipline',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='catalogmoc',
            name='mooc',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='catalogmoc',
            name='note',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='catalogmoc',
            name='url',
            field=models.TextField(default='null'),
        ),
    ]
