# Generated by Django 3.1.5 on 2021-01-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_mooc', '0002_auto_20210106_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogmoc',
            name='discipline',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='catalogmoc',
            name='mooc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='catalogmoc',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='catalogmoc',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
