# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-20 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20181221_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='university',
            field=models.TextField(blank=True, null=True),
        ),
    ]
